import '../split_section_def.dart';

// Curated sub-sections: quads (muscle: legs). Display order = list order (compounds first). Section keys are stable ids; do not
// rename them. Sections that share a `family` are one sub-area split to stay <= 13 exercises each.
const List<SectionDef> sectionsQuads = [
  SectionDef(
    'quads',
    'Quads · Barbell squats',
    'Barbell squats and deadlift variants for the front of the thigh.',
    [
      'back_squat',
      'front_squat',
      'low_bar_squat',
      'pause_squat',
      'box_squat',
      'safety_bar_squat',
      'zercher_squat',
      'smith_machine_squat',
      'landmine_squat',
      'trap_bar_deadlift',
      'sumo_deadlift',
    ],
  ),
  SectionDef(
    'quads_goblet',
    'Quads · Goblet, kettlebell & band squats',
    'Lighter squat variations with dumbbells, kettlebells, sandbags or bands.',
    [
      'goblet_squat',
      'kb_front_rack_squat',
      'sandbag_squat',
      'kb_thruster',
      'band_squat',
    ],
    family: 'quads',
  ),
  SectionDef(
    'quads_press',
    'Quads · Leg press & squat machines',
    'Leg presses and plate-loaded or hack-style squat machines.',
    [
      'leg_press',
      'hack_squat',
      'v_squat_machine',
      'reverse_hack_squat',
      'pendulum_squat',
      'belt_squat',
      'leg_press_feet_low',
      'leg_press_feet_high',
      'leg_press_wide_stance',
      'horizontal_leg_press',
      'single_leg_press',
    ],
    family: 'quads',
  ),
  SectionDef(
    'lunges',
    'Lunges · Split squats & lunges',
    'Split squats and lunges for unilateral leg strength.',
    [
      'bulgarian_split_squat',
      'db_split_squat',
      'barbell_split_squat',
      'smith_split_squat',
      'walking_lunge',
      'barbell_walking_lunge',
      'reverse_lunge',
      'smith_reverse_lunge',
      'kb_reverse_lunge',
      'forward_lunge',
      'db_curtsy_lunge',
    ],
  ),
  SectionDef(
    'lunges_step',
    'Lunges · Step-ups, lateral & sumo',
    'Step-ups and lateral or wide-stance single-leg work.',
    [
      'db_step_up',
      'barbell_step_up',
      'step_up',
      'lateral_lunge',
      'cossack_squat',
      'kb_cossack_squat',
      'db_sumo_squat',
      'kb_sumo_squat',
    ],
    family: 'lunges',
  ),
  SectionDef(
    'lunges_sled',
    'Lunges · Sleds, yokes & carries',
    'Sled pushes, drags, yoke walks and sandbag carries.',
    ['sled_push', 'backward_sled_drag', 'yoke_walk', 'sandbag_carry'],
    family: 'lunges',
  ),
  SectionDef(
    'quad_iso',
    'Quad isolation & bodyweight',
    'Extensions and bodyweight work for the quads.',
    [
      'leg_extension',
      'single_leg_extension',
      'spanish_squat',
      'sissy_squat',
      'reverse_nordic_curl',
      'pistol_squat',
      'shrimp_squat',
      'bodyweight_squat',
      'wall_sit',
    ],
  ),
];
