import '../split_section_def.dart';

// Curated sub-sections: hamstrings_glutes (muscle: legs). Display order = list order (compounds first). Section keys are stable ids; do not
// rename them. Sections that share a `family` are one sub-area split to stay <= 13 exercises each.
const List<SectionDef> sectionsHamstringsGlutes = [
  SectionDef(
    'hams',
    'Hamstrings · Hinges',
    'Romanian and stiff-leg deadlifts for the back of the thigh.',
    [
      'rdl',
      'db_rdl',
      'kb_rdl',
      'cable_rdl',
      'smith_rdl',
      'stiff_leg_deadlift',
      'db_stiff_leg_deadlift',
      'single_leg_rdl',
      'kb_single_leg_rdl',
    ],
  ),
  SectionDef(
    'hams_curl',
    'Hamstrings · Leg curls',
    'Machine, cable, dumbbell and band leg curls.',
    [
      'leg_curl',
      'seated_leg_curl',
      'standing_leg_curl',
      'standing_cable_leg_curl',
      'db_leg_curl',
      'band_leg_curl',
    ],
    family: 'hams',
  ),
  SectionDef(
    'hams_bodyweight',
    'Hamstrings · Sliders & Nordics',
    'Sliding curls, stability-ball curls, Nordics and glute-ham raises.',
    [
      'slider_leg_curl',
      'single_leg_slider_curl',
      'stability_ball_leg_curl',
      'nordic_curl',
      'nordic_curl_machine',
      'glute_ham_raise',
    ],
    family: 'hams',
  ),
  SectionDef(
    'glutes',
    'Glutes · Bridges & thrusts',
    'Hip thrusts and glute bridges.',
    [
      'hip_thrust',
      'machine_hip_thrust',
      'smith_hip_thrust',
      'db_hip_thrust',
      'band_hip_thrust',
      'single_leg_hip_thrust',
      'glute_bridge',
      'barbell_glute_bridge',
      'db_glute_bridge',
      'band_glute_bridge',
      'single_leg_glute_bridge',
      'frog_pump',
    ],
  ),
  SectionDef(
    'glutes_hinge',
    'Glutes · Kettlebell & cable hinges',
    'Pull-throughs, swings and kettlebell hinges.',
    [
      'cable_pull_through',
      'band_pull_through',
      'kb_sumo_deadlift',
      'kettlebell_swing',
      'kb_single_arm_swing',
      'kb_clean',
      'kb_snatch',
    ],
    family: 'glutes',
  ),
  SectionDef(
    'glutes_kick',
    'Glutes · Kickbacks',
    'Cable, machine and bodyweight kickbacks.',
    [
      'cable_kickback',
      'glute_kickback_machine',
      'donkey_kick',
      'band_donkey_kick',
    ],
    family: 'glutes',
  ),
  SectionDef(
    'glutes_abduct',
    'Glutes · Hip abduction',
    'Abduction, clamshells and band walks for the side glutes.',
    [
      'fire_hydrant',
      'hip_abduction_machine',
      'cable_hip_abduction',
      'side_lying_hip_abduction',
      'clamshell',
      'band_clamshell',
      'band_standing_hip_abduction',
      'side_plank_hip_abduction',
      'band_lateral_walk',
      'monster_walk',
    ],
    family: 'glutes',
  ),
  SectionDef(
    'glutes_adduct',
    'Glutes · Adductors',
    'Hip adduction for the inner thigh.',
    [
      'hip_adduction_machine',
      'cable_hip_adduction',
      'band_hip_adduction',
      'side_lying_hip_adduction',
    ],
    family: 'glutes',
  ),
];
