import '../split_section_def.dart';

// Curated sub-sections: back (muscle: back). Display order = list order (compounds first). Section keys are stable ids; do not
// rename them. Sections that share a `family` are one sub-area split to stay <= 13 exercises each.
const List<SectionDef> sectionsBack = [
  SectionDef(
    'lats',
    'Lats · Pull-ups',
    'Pull-up and chin-up variations for lat width.',
    [
      'pullup',
      'chinup',
      'neutral_grip_pullup',
      'wide_grip_pullup',
      'weighted_pullup',
      'commando_pullup',
      'archer_pullup',
      'towel_pullup',
      'assisted_pullup',
    ],
  ),
  SectionDef(
    'lats_pulldown',
    'Lats · Pulldowns',
    'Cable, machine and band pulldowns for lat width.',
    [
      'lat_pulldown',
      'close_grip_pulldown',
      'reverse_grip_pulldown',
      'machine_pulldown',
      'plate_loaded_pulldown',
      'iso_lateral_pulldown',
      'band_lat_pulldown',
      'single_arm_pulldown',
    ],
    family: 'lats',
  ),
  SectionDef(
    'lats_pullover',
    'Lats · Pullovers & straight-arm',
    'Straight-arm pulldowns and pullovers to isolate the lats.',
    ['straight_arm_pulldown', 'db_pullover', 'pullover_machine'],
    family: 'lats',
  ),
  SectionDef(
    'upper',
    'Upper back · Barbell & dumbbell rows',
    'Free-weight rows for thickness and the mid back.',
    [
      'barbell_row',
      'pendlay_row',
      'yates_row',
      'underhand_barbell_row',
      'meadows_row',
      'landmine_row',
      'tbar_row',
      'seal_row',
      'smith_bent_over_row',
      'db_bent_over_row',
      'kroc_row',
      'db_row',
    ],
  ),
  SectionDef(
    'upper_cable',
    'Upper back · Machine & cable rows',
    'Cable and machine rows with a fixed, easy-to-load path.',
    [
      'seated_cable_row',
      'wide_grip_cable_row',
      'high_cable_row',
      'underhand_cable_row',
      'one_arm_cable_row',
      'high_row_machine',
      'iso_lateral_row',
      'seated_row_machine',
      'chest_supported_row',
      'chest_supported_db_row',
    ],
    family: 'upper',
  ),
  SectionDef(
    'upper_bodyweight',
    'Upper back · Inverted, band & kettlebell rows',
    'Bodyweight, band and kettlebell rows.',
    [
      'inverted_row',
      'feet_elevated_inverted_row',
      'band_row',
      'kb_row',
      'kb_gorilla_row',
      'renegade_row',
    ],
    family: 'upper',
  ),
  SectionDef(
    'traps',
    'Traps',
    'Shrugs, rack pulls and Y raises for the traps.',
    [
      'barbell_shrug',
      'db_shrug',
      'cable_shrug',
      'trap_bar_shrug',
      'smith_shrug',
      'machine_shrug',
      'behind_back_shrug',
      'incline_db_shrug',
      'kb_shrug',
      'rack_pull',
      'barbell_high_pull',
      'prone_y_raise',
      'scapular_pullup',
    ],
  ),
  SectionDef(
    'lower',
    'Lower back',
    'Hinges and extensions for the spinal erectors.',
    [
      'deadlift',
      'deficit_deadlift',
      'snatch_grip_deadlift',
      'db_deadlift',
      'kb_deadlift',
      'back_extension',
      'back_extension_machine',
      'weighted_back_extension',
      'good_morning',
      'db_good_morning',
      'band_good_morning',
      'reverse_hyperextension',
      'superman',
    ],
  ),
];
